"""Shared domain contracts for incidents, events, the lifecycle, and product surface."""

from incident_contracts.agent_context import AgentRunContext
from incident_contracts.api_models import (
    ApproveIncidentRequest,
    RejectIncidentRequest,
    RemediateIncidentRequest,
    SimulateIncidentRequest,
)
from incident_contracts.enums import (
    ActorKind,
    ApprovalStatus,
    EventType,
    EvidenceKind,
    IncidentStatus,
    ScenarioId,
    Severity,
    ToolClass,
)
from incident_contracts.errors import (
    DomainError,
    DuplicateRemediationError,
    IllegalTransitionError,
    IncidentNotFoundError,
    InvalidApprovalError,
)
from incident_contracts.keys import event_sk, incident_pk, parse_event_sk, parse_incident_pk
from incident_contracts.lifecycle import ALLOWED_TRANSITIONS, transition
from incident_contracts.models import (
    Approval,
    Deployment,
    Diagnosis,
    Evidence,
    Incident,
    IncidentEvent,
    IncidentFixture,
    LogSample,
    MetricSample,
    TelemetryBundle,
)
from incident_contracts.repository import IncidentRepository, InMemoryIncidentRepository
from incident_contracts.service import IncidentService
from incident_contracts.surface import (
    API_OPERATIONS,
    COST_LIMITS_CLIENT_WRITABLE,
    DASHBOARD_ROUTES,
    DEMO_SCRIPT_STEPS,
    DEMO_SERVICES,
    INCIDENT_DETAIL_SECTIONS,
    INVESTIGATION_TOOLS,
    REQUIRED_AUDIT_EVENT_TYPES,
    ApiOperation,
    HttpMethod,
    mutating_operations,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "API_OPERATIONS",
    "COST_LIMITS_CLIENT_WRITABLE",
    "DASHBOARD_ROUTES",
    "DEMO_SCRIPT_STEPS",
    "DEMO_SERVICES",
    "INCIDENT_DETAIL_SECTIONS",
    "INVESTIGATION_TOOLS",
    "REQUIRED_AUDIT_EVENT_TYPES",
    "ActorKind",
    "AgentRunContext",
    "ApiOperation",
    "Approval",
    "ApprovalStatus",
    "ApproveIncidentRequest",
    "Deployment",
    "Diagnosis",
    "DomainError",
    "DuplicateRemediationError",
    "EventType",
    "Evidence",
    "EvidenceKind",
    "HttpMethod",
    "IllegalTransitionError",
    "InMemoryIncidentRepository",
    "Incident",
    "IncidentEvent",
    "IncidentFixture",
    "IncidentNotFoundError",
    "IncidentRepository",
    "IncidentService",
    "IncidentStatus",
    "InvalidApprovalError",
    "LogSample",
    "MetricSample",
    "RejectIncidentRequest",
    "RemediateIncidentRequest",
    "ScenarioId",
    "Severity",
    "SimulateIncidentRequest",
    "TelemetryBundle",
    "ToolClass",
    "event_sk",
    "incident_pk",
    "mutating_operations",
    "parse_event_sk",
    "parse_incident_pk",
    "transition",
]
