"""Shared domain contracts for incidents, events, the lifecycle, and product surface."""

from incident_contracts.actors import format_actor, parse_actor, validate_actor
from incident_contracts.agent_context import AgentRunContext
from incident_contracts.api_models import (
    ApproveIncidentRequest,
    RejectIncidentRequest,
    RemediateIncidentRequest,
    SimulateIncidentRequest,
)
from incident_contracts.enums import (
    ActorKind,
    ApprovalStatus,
    EventType,
    EvidenceKind,
    IncidentStatus,
    ScenarioId,
    Severity,
    ToolClass,
)
from incident_contracts.errors import (
    DomainError,
    DuplicateRemediationError,
    IllegalTransitionError,
    IncidentNotFoundError,
    InvalidActorError,
    InvalidApprovalError,
    InvalidIncidentEventError,
    UnsupportedSchemaVersionError,
)
from incident_contracts.events import (
    DEFAULT_EVENT_SOURCE,
    INCIDENT_DETECTED_DETAIL_TYPE,
    SUPPORTED_SCHEMA_VERSION,
    IncidentDetectedV1,
    detected_event_from_fixture,
    incident_detected_v1_schema,
    incident_from_detected,
    incident_id_for_event,
    parse_incident_detected,
)
from incident_contracts.keys import (
    INDEX_SK,
    METADATA_SK,
    deployment_pk,
    deployment_sk,
    event_id_pk,
    event_sk,
    idempotency_pk,
    incident_pk,
    parse_event_sk,
    parse_incident_pk,
    simulation_pk,
    source_event_pk,
)
from incident_contracts.lifecycle import ALLOWED_TRANSITIONS, transition
from incident_contracts.models import (
    Approval,
    Deployment,
    Diagnosis,
    Evidence,
    Incident,
    IncidentEvent,
    IncidentFixture,
    LogSample,
    MetricSample,
    TelemetryBundle,
)
from incident_contracts.repository import IncidentRepository, InMemoryIncidentRepository
from incident_contracts.service import IncidentService
from incident_contracts.surface import (
    API_OPERATIONS,
    COST_LIMITS_CLIENT_WRITABLE,
    DASHBOARD_ROUTES,
    DEMO_SCRIPT_STEPS,
    DEMO_SERVICES,
    INCIDENT_DETAIL_SECTIONS,
    INVESTIGATION_TOOLS,
    REQUIRED_AUDIT_EVENT_TYPES,
    ApiOperation,
    HttpMethod,
    mutating_operations,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "API_OPERATIONS",
    "COST_LIMITS_CLIENT_WRITABLE",
    "DASHBOARD_ROUTES",
    "DEFAULT_EVENT_SOURCE",
    "DEMO_SCRIPT_STEPS",
    "DEMO_SERVICES",
    "INCIDENT_DETAIL_SECTIONS",
    "INCIDENT_DETECTED_DETAIL_TYPE",
    "INDEX_SK",
    "INVESTIGATION_TOOLS",
    "METADATA_SK",
    "REQUIRED_AUDIT_EVENT_TYPES",
    "SUPPORTED_SCHEMA_VERSION",
    "ActorKind",
    "AgentRunContext",
    "ApiOperation",
    "Approval",
    "ApprovalStatus",
    "ApproveIncidentRequest",
    "Deployment",
    "Diagnosis",
    "DomainError",
    "DuplicateRemediationError",
    "EventType",
    "Evidence",
    "EvidenceKind",
    "HttpMethod",
    "IllegalTransitionError",
    "InMemoryIncidentRepository",
    "Incident",
    "IncidentDetectedV1",
    "IncidentEvent",
    "IncidentFixture",
    "IncidentNotFoundError",
    "IncidentRepository",
    "IncidentService",
    "IncidentStatus",
    "InvalidActorError",
    "InvalidApprovalError",
    "InvalidIncidentEventError",
    "LogSample",
    "MetricSample",
    "RejectIncidentRequest",
    "RemediateIncidentRequest",
    "ScenarioId",
    "Severity",
    "SimulateIncidentRequest",
    "TelemetryBundle",
    "ToolClass",
    "UnsupportedSchemaVersionError",
    "deployment_pk",
    "deployment_sk",
    "detected_event_from_fixture",
    "event_id_pk",
    "event_sk",
    "format_actor",
    "idempotency_pk",
    "incident_detected_v1_schema",
    "incident_from_detected",
    "incident_id_for_event",
    "incident_pk",
    "mutating_operations",
    "parse_actor",
    "parse_event_sk",
    "parse_incident_detected",
    "parse_incident_pk",
    "simulation_pk",
    "source_event_pk",
    "transition",
    "validate_actor",
]
